spring:
  datasource:
    url: jdbc:mysql://182.92.116.109:3306/tutor-it-video?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: wqq123
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
  # Redis 相关配置
  redis:
    host: ring2.xyz # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
  application:
    name: tutor-it-video
  boot:
    admin:
      client:
        url: http://localhost:8769
        instance:
          service-url: http://localhost:${server.port}
        username: user
        password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 119.3.190.45:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
redis:
  key:
    prefix: "tutor-admin"
# mybatis plus 配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: assign_id
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8086
# JWT配置
jwt:
  # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenHead: tutor-it
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400
  # 配置不需要认证的接口
  antMatchers: /portal/**,/core/customer/**,/login/**,/favicon.ico,/captcha,/actuator/**,/goods/test,/download/**
ribbon:
  eager-load:
    enabled: true
    clients: tutor-media
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 50000
    time-to-live: 9000
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 60000