spring:
  application:
    name: core-recommend
  cloud:
    nacos:
      discovery:
        server-addr: 119.3.190.45:8848
  datasource:
    url: jdbc:mysql://localhost:3306/tutor-it-order?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: wqq123
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8888